services:
  - type: web
    name: ski-calendar-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      BOT_TOKEN:
        sync: false
